eureka:
  build: ./eureka
  ports:
    - "8761:8761"
simple1:
  build: ./simple1
  links:
   - eureka
railsdemo:
  build: ./RailsEurekaClient
  links:
   - eureka
  ports:
   - "3000:3000"
simple2:
  build: ./simple2
  links:
   - eureka
zuul:
  build: ./zuul
  links:
   - eureka
  ports:
    - "8080:8080"