server:
  port: 9090

spring:
  application:
    name: sidecar

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    healthCheckUrlPath: /health
    preferIpAddress: true
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG


sidecar:
  port: 3000
  health-uri: http://192.168.0.144:3000/health.json